os: linux
sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 2.7
        - python: 3.5
          if: branch =~ ^release.* OR branch =~ ^master
        - python: 3.6
        - python: 3.7
          dist: xenial
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: PYVER=py27
          if: branch =~ ^release.* OR branch =~ ^master
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: PYVER=py36

# command to install dependencies
install:
  - ./.ci/travis/install.sh
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# command to run tests
script: 
  - ulimit -n 2048 # Error with py3 and OSX, max file descriptors
  - ./.ci/travis/run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
